### ISSUE TITLE
docs: add file names in Add Subscriptions to Ticket Search Form lab exercise

### ISSUE THREAD

**Issue by lcihaeon** [nrwl/workshop-nx-labs#23]
### Code Instructions

1. In `search-tickets.component.ts`, subscribe to `assignedToUser.valueChanges` and make a call to the `UserService.users` method (pass in the `value` for the search term). Subscribe to that and wire up the `users` class field to the results.

  ```js
  ngOnInit() {
    this.subscription = this.assignedToUser... // Update this code
  }
  ```

<br/>

2.  In `search-tickets.component.ts`, save the `subscription` reference and implement `OnDestroy` to unsubscribe from the subscription.

  ```js
  ngOnDestroy() {
    // <YOUR - CODE - HERE>
  }
  ```

<br/>

3.  In `search-tickets.component.ts`, the Ticket Search will display a list of matching tickets using `searchResults$ | async`. When the `submit` button is clicked, search for tickets using `TicketService.searchTickets`.

  ```js
  submit() {
      this.searchResults$ = this.ticketService.searchTickets(<TICKET-SEARCH-TERM>, <ASSIGNED-USER>);
  }
  ```
  
<br/>  

4. In `search-tickets.component.html`, use an `*ngFor` template directive to display the list of users for the suggest-on-type feature. Make use of the `User::fullName` for both the label the value to pass to the `setAssignedToUser` class method.

  ```html
    <ul>
      <li *ngFor="let user of users" (click)="setAssignedToUser('name')"> 
          {{user.fullName}}
      </li>
    </ul>
  ```
  
<br/>

**Comment by ThomasBurleson** [comment]
@lcihaeon  - fixed. eg. https://github.com/nrwl/workshop-nx-labs/blob/master/rxjs/lab-5.md
